import mongoose from "mongoose";
import mongoosePaginate from "mongoose-paginate-v2";

mongoose.plugin(mongoosePaginate);

/**
 * @description Learning Path Schema and Model (Route)
 * @summary Acts as the primary container for an educational journey. It stores 
 * the card structure, version control, difficulty metadata, and AI consumption 
 * statistics. It serves as the central hub connecting users with generated content.
 * Includes: Version management, card counters, and quality metrics.
 * @prop {string} title - The display name of the learning path.
 * @prop {string} topic - Main subject tag (e.g., 'Programming', 'History').
 * @prop {string} description - Detailed overview of the route's purpose.
 * @prop {ObjectId} authorId - Route creator. Null indicates system/AI generation.
 * @prop {ObjectId[]} cardIds - Array of references to associated Card documents.
 * @prop {number} cardCount - Total number of cards within the route.
 * @prop {number} currentVersion - Incremental version number.
 * @prop {ObjectId} latestVersionId - Reference to the RouteVersion history document.
 * @prop {string[]} tags - Descriptive keywords for categorization.
 * @prop {string} language - ISO language code (default: 'es').
 * @prop {number} metadata.estimatedDurationMin - Total estimated completion time.
 * @prop {string} metadata.difficulty - Complexity level: 'low', 'medium', or 'high'.
 * @prop {string} metadata.createdFromPrompt - Original prompt text that initiated the route.
 * @prop {Object} tokenUsage - AI cost tracking (input/output tokens and USD cost).
 * @prop {number} ratingAvg - Weighted average of user ratings (0.0 - 5.0).
 * @prop {boolean} isPremiumOnly - Restricts access based on user subscription tier.
 * @prop {boolean} deleted - Logical deletion flag (Soft Delete).
 * @prop {Date} deletedAt - Timestamp of logical deletion.
 * @prop {ObjectId} deletedBy - Reference to the user who performed the deletion.
 * @author Daniel Arapé
 */
const routeSchema = new mongoose.Schema(
  {
    // --- Basic Information ---
    title: {
      type: String,
      required: true,
      trim: true,
    },
    topic: {
      type: String,
      trim: true,
      description:
        "Main subject label (e.g. 'Programming', 'History')",
    },
    description: {
      type: String,
      trim: true,
    },
    authorId: {
      type: Schema.Types.ObjectId,
      ref: "User",
      default: null,
      description:
        "Route creator. Null indicates it was generated by the system/AI.",
    },

    // --- Structure and Versions ---
    cardIds: [
      {
        type: Schema.Types.ObjectId,
        ref: "Card",
      },
    ],
    cardCount: {
      type: Number,
      default: 0,
    },
    currentVersion: {
      type: Number,
      default: 1,
    },
    latestVersionId: {
      type: Schema.Types.ObjectId,
      ref: "RouteVersion",
      description: "Reference to the version history document",
    },

    // --- Classification and Metadata ---
    tags: [String],
    language: {
      type: String,
      default: "es",
    },
    metadata: {
      estimatedDurationMin: { type: Number, default: 0 },
      difficulty: {
        type: String,
        enum: ["low", "medium", "high"],
        default: "medium",
      },
      createdFromPrompt: {
        type: String,
        description: "Original prompt text that gave rise to this route",
      },
    },

    // --- AI Statistics (Costs) ---
    tokenUsage: {
      inputTokens: { type: Number, default: 0 },
      outputTokens: { type: Number, default: 0 },
      costUsd: { type: Number, default: 0 },
      lastUpdatedAt: { type: Date },
    },

    // --- Social and Status ---
    ratingAvg: {
      type: Number,
      default: 0,
      min: 0,
      max: 5,
    },
    ratingCount: {
      type: Number,
      default: 0,
    },
    isPremiumOnly: {
      type: Boolean,
      default: false,
    },
    published: {
      type: Boolean,
      default: true,
    },

    // --- Logical Deletion Control ---
    deleted: { type: Boolean, default: false },
    deletedAt: { type: Date, default: null },
    deletedBy: { type: Schema.Types.ObjectId, ref: "User", default: null },
  },
  {
    timestamps: true,
  }
);

const Route = mongoose.model("Route", routeSchema);

export default Route;